# Crown Plugin Configuration

# Crown item properties
crown:
  # Material for the crown (GOLDEN_HELMET, DIAMOND_HELMET, etc.)
  material: GOLDEN_HELMET
  
  # Display name of the crown (supports color codes with &)
  name: "&6The Crown"
  
  # Lore text shown on the crown (supports color codes with &)
  lore:
    - "&7A majestic crown worn by the leader"
    - "&7Grants +2 extra hearts"
    - "&e&lOnly for the rightful owner"
  
  # Additional health granted to the wearer (2.0 = 1 heart)
  health_bonus: 4.0
  
  # Armor value (3.0 = netherite helmet equivalent)
  armor: 3.0
  
  # Apply curse of binding (true/false)
  binding_curse: true
  
  # Additional enchantments to apply to the crown
  # Format: ENCHANTMENT_NAME: level
  enchantments:
    PROTECTION_ENVIRONMENTAL: 4
    OXYGEN: 3
    WATER_WORKER: 1

# Crown behavior settings
behavior:
  # Auto-equip the crown when given to a player or transferred to killer (true/false)
  auto_equip_on_give: true
  
  # Transfer crown to killer when the crown holder is killed (true/false)
  transfer_on_kill: true
  
  # Allow players to drop the crown (true/false)
  allow_dropping: false

  # Prioritize transfer to killer over dropping the crown on death (true/false). (Only when allow_dropping is true)
  prioritize_transfer: false
  
  # Remove crown from player data on death when the crown is dropped (true/false). It will be dropped or just removed based on allow_dropping.
  remove_crown_on_death: false

# Messages
messages:
  prefix: "&6[Crown] &r"
  crown_given: "&aYou have been given the crown!"
  crown_removed: "&cYour crown has been removed!"
  crown_transferred: "&aYou obtained the crown by defeating its previous owner!"
  no_permission: "&cYou don't have permission to use this command!"
  player_not_found: "&cPlayer not found!"
  config_reloaded: "&aConfiguration reloaded!" 