# Crown Plugin Configuration

# Crown item properties
crown:
  # Material for the crown (GOLDEN_HELMET, DIAMOND_HELMET, etc.)
  material: GOLDEN_HELMET
  
  # Display name of the crown (supports color codes with &)
  name: "&6The Crown"
  
  # Lore text shown on the crown (supports color codes with &)
  lore:
    - "&7A majestic crown worn by the leader"
    - "&7Grants +2 extra hearts"
    - "&e&lOnly for the rightful owner"
  
  # Additional health granted to the wearer (2.0 = 1 heart)
  health_bonus: 4.0
  
  # Armor value (3.0 = netherite helmet equivalent)
  armor: 3.0
  
  # Apply curse of binding (true/false)
  binding_curse: true
  
  # Additional enchantments to apply to the crown
  # Format: ENCHANTMENT_NAME: level
  enchantments:
    PROTECTION_ENVIRONMENTAL: 4
    OXYGEN: 3
    WATER_WORKER: 1

# Crown behavior settings
behavior:
  # Auto-equip the crown when given to a player or transferred to killer (true/false)
  auto_equip_on_give: true
  
  # Transfer crown to killer when the crown holder is killed (true/false)
  transfer_on_kill: true
  
  # Allow players to drop the crown (true/false)
  allow_dropping: false

  # Prioritize transfer to killer over dropping the crown on death (true/false). (Only when allow_dropping is true)
  prioritize_transfer: false
  
  # Remove crown from player data on death when the crown is dropped (true/false). It will be dropped or just removed based on allow_dropping.
  remove_crown_on_death: false

# Particle effects when someone becomes leader
particles:
  # Enable particle effects when someone becomes leader (true/false)
  enabled: true
  
  # Particle type to use
  # Available particle types:
  # Basic: EXPLOSION_NORMAL, EXPLOSION_LARGE, EXPLOSION_HUGE, FIREWORKS_SPARK
  # Water: WATER_BUBBLE, WATER_SPLASH, WATER_WAKE, DRIP_WATER, WATER_DROP
  # Combat: CRIT, CRIT_MAGIC, SMOKE_NORMAL, SMOKE_LARGE
  # Magic: SPELL, SPELL_INSTANT, SPELL_MOB, SPELL_MOB_AMBIENT, SPELL_WITCH
  # Environment: SUSPENDED, SUSPENDED_DEPTH, TOWN_AURA, CLOUD, FOOTSTEP
  # Special: PORTAL, ENCHANTMENT_TABLE, LAVA, DRIP_LAVA, FLAME
  # Villager: VILLAGER_ANGRY, VILLAGER_HAPPY
  # Items: NOTE, HEART, BARRIER, ITEM_CRACK, BLOCK_CRACK, BLOCK_DUST, ITEM_TAKE
  # Other: SNOWBALL, SNOW_SHOVEL, SLIME, MOB_APPEARANCE
  # Colored: REDSTONE (supports color config), DUST (supports color config)
  type: FLAME
  
  # Number of particles to spawn
  count: 10
  
  # Duration of the particle effect in ticks (20 ticks = 1 second)
  duration: 20
  
  # Offset from player position (x, y, z)
  offset:
    x: 0.3
    y: 1.8
    z: 0.3
  
  # Speed of particles (0.1 = slow, 1.0 = fast)
  speed: 0.2
  
  # Color for colored particles (RGB values 0-255)
  # Only applies to REDSTONE and DUST particle types
  color:
    red: 255
    green: 215
    blue: 0

# Messages
messages:
  prefix: "&6[Crown] &r"
  crown_given: "&aYou have been given the crown!"
  crown_removed: "&cYour crown has been removed!"
  crown_transferred: "&aYou obtained the crown by defeating its previous owner!"
  no_permission: "&cYou don't have permission to use this command!"
  player_not_found: "&cPlayer not found!"
  config_reloaded: "&aConfiguration reloaded!" 